kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mongodb
  name: px-mongo-mongodb
spec:
  storageClassName: mongo-sc
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 500Gi