apiVersion: apps/v1
kind: Deployment
metadata:
  name: ycsb
  labels:
    app: ycsb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ycsb
  template:
    metadata:
      labels:
        app: ycsb
    spec:
      containers:
      - name: ycsb
        image: alvarobrandon/ycsb:latest
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ["/bin/sh"]
        args: ["-c", "ycsb-0.12.0/bin/ycsb.sh load mongodb -s -P ycsb-0.12.0/workloads/workloada -p recordcount=100000000 -p mongodb.url=mongodb://10-233-98-25.$(POD_NAMESPACE).pod.cluster.local:27017/ycsb?w=0;ycsb-0.12.0/bin/ycsb.sh run mongodb -s -P ycsb-0.12.0/workloads/workloada -p recordcount=100000000 -p mongodb.url=mongodb://10-233-98-25.$(POD_NAMESPACE).pod.svc.cluster.local:27017/ycsb?w=0"]
      restartPolicy: Always