kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sysbench-mysql-data
spec:
  storageClassName: sysbench-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi