# Azure sysbench storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sysbench-sc
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: pwxautomation